### ISSUE TITLE
Negative filtering

### ISSUE THREAD

**Issue by ylavoie** [pierreforstmann/pg_log_statements#1]
I've searching for this utility for a long time! Thanks for providing.

Filtering is already great but is only allows adding databases.

Is there a way to forbid logging for selected databases? I'm looking for a way to prevent queries to the system Catalog (`pg_database`, `pg_stat*`, ...) to pollute logfiles.

**Comment by pierreforstmann** [comment]
Currently there is no way to forbid logging for selected databases.

Note that PostgreSQL system catalog is the schema `pg_catalog` available in every database. My extension `pg_log_statements` is only using `log_statement` parameter to enable logging. As far as I know there is no easy way to filter logging based on  schema used by SQL statement because there is no hook to customize logging.

**Comment by pierreforstmann** [comment]
Issue closed.
